// <auto-generated />
using System;
using Assignment_3_New.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Assignment_3_New.Migrations
{
    [DbContext(typeof(GroceryContext))]
    [Migration("20220130181656_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21");

            modelBuilder.Entity("Assignment_3_New.Models.Customer", b =>
                {
                    b.Property<string>("customerID")
                        .HasColumnType("TEXT");

                    b.Property<string>("address")
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .HasColumnType("TEXT");

                    b.Property<string>("firstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("lastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("password")
                        .HasColumnType("TEXT");

                    b.Property<int>("phoneNum")
                        .HasColumnType("INTEGER");

                    b.HasKey("customerID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Assignment_3_New.Models.Driver", b =>
                {
                    b.Property<string>("driverID")
                        .HasColumnType("TEXT");

                    b.Property<string>("carMake")
                        .HasColumnType("TEXT");

                    b.Property<string>("carModel")
                        .HasColumnType("TEXT");

                    b.Property<string>("firstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("lastName")
                        .HasColumnType("TEXT");

                    b.HasKey("driverID");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("Assignment_3_New.Models.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("customerID")
                        .HasColumnType("TEXT");

                    b.Property<string>("driverID")
                        .HasColumnType("TEXT");

                    b.Property<double>("totalPrice")
                        .HasColumnType("REAL");

                    b.HasKey("OrderID");

                    b.HasIndex("customerID");

                    b.HasIndex("driverID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Assignment_3_New.Models.Order", b =>
                {
                    b.HasOne("Assignment_3_New.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("customerID");

                    b.HasOne("Assignment_3_New.Models.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("driverID");
                });
#pragma warning restore 612, 618
        }
    }
}
